// packages/angular/src/lib/hooks.ts
import {
  inject,
  DestroyRef,
  type Signal,
  signal,
} from "@angular/core";
import type {
  ThemeRuntime,
  ThemeDefinition,
  ThemeMode,
  ThemeRuntimeSnapshot,
  ThemePack,
  HistoryEntry,
  ThemeLifecycleEventName,
  ThemeScheduleState,
  ThemeScheduleSetOptions,
} from "@theme-kit/core";
import { EMPTY_THEME_SCHEDULE_STATE } from "@theme-kit/core";
import { THEME_KIT_RUNTIME, THEME_KIT_SCOPED_RUNTIME } from "./tokens";

function resolveRuntime<T extends ThemeDefinition>(): ThemeRuntime<T> {
  const runtime =
    inject(THEME_KIT_SCOPED_RUNTIME, { optional: true }) ??
    inject(THEME_KIT_RUNTIME);
  if (!runtime) {
    throw new Error(
      "No ThemeKit runtime found. Ensure provideThemeKit() is included in your providers.",
    );
  }
  return runtime as ThemeRuntime<T>;
}

export function injectThemeRuntime<T extends ThemeDefinition = ThemeDefinition>(): ThemeRuntime<T> {
  return resolveRuntime<T>();
}

export interface ThemeState<T extends ThemeDefinition = ThemeDefinition> {
  theme: T;
  mode: ThemeMode;
  family: string;
  resolvedMode: "light" | "dark";
  setMode: (mode: ThemeMode) => void;
  setFamily: (family: string) => void;
  toggleTheme: () => void;
}

export function injectTheme<T extends ThemeDefinition = ThemeDefinition>(): Signal<ThemeState<T>> {
  const runtime = resolveRuntime<T>();
  const destroyRef = inject(DestroyRef);

  const state = signal<ThemeState<T>>({
    theme: runtime.store.get() as T,
    mode: runtime.selection.getMode(),
    family: runtime.selection.getFamily(),
    resolvedMode:
      runtime.store.get().meta?.mode === "dark" ? "dark" : "light",
    setMode: (m: ThemeMode) => runtime.selection.setMode(m),
    setFamily: (f: string) => runtime.selection.setFamily(f),
    toggleTheme: () => runtime.selection.toggleTheme(),
  });

  const unsub = runtime.store.subscribe((t) => {
    state.set({
      theme: t as T,
      mode: runtime.selection.getMode(),
      family: runtime.selection.getFamily(),
      resolvedMode: t.meta?.mode === "dark" ? "dark" : "light",
      setMode: state().setMode,
      setFamily: state().setFamily,
      toggleTheme: state().toggleTheme,
    });
  });

  destroyRef.onDestroy(unsub);

  return state.asReadonly();
}

export interface ThemeHistoryState {
  canUndo: boolean;
  canRedo: boolean;
}

export function injectThemeHistory<T extends ThemeDefinition = ThemeDefinition>() {
  const runtime = resolveRuntime<T>();
  const destroyRef = inject(DestroyRef);

  const state = signal<ThemeHistoryState>({
    canUndo: runtime.history.canUndo(),
    canRedo: runtime.history.canRedo(),
  });

  const unsub = runtime.store.subscribe(() => {
    state.set({
      canUndo: runtime.history.canUndo(),
      canRedo: runtime.history.canRedo(),
    });
  });

  destroyRef.onDestroy(unsub);

  return {
    history: state.asReadonly(),
    undo: () => runtime.history.undo(),
    redo: () => runtime.history.redo(),
    clear: () => runtime.history.clear(),
  };
}

export function injectThemeBatch() {
  const runtime = resolveRuntime();
  return (callback: () => void) => runtime.batch(callback);
}

export function injectThemeSnapshot() {
  const runtime = resolveRuntime();
  return () => runtime.snapshot() as ThemeRuntimeSnapshot;
}

export function injectThemeRestore() {
  const runtime = resolveRuntime();
  return (snapshot: ThemeRuntimeSnapshot) => runtime.restore(snapshot);
}

export function injectThemeTimeTravel<T extends ThemeDefinition = ThemeDefinition>() {
  const runtime = resolveRuntime<T>();
  const destroyRef = inject(DestroyRef);

  const historySignal = signal<readonly HistoryEntry<T>[]>(runtime.history.getHistory());

  const unsub = runtime.store.subscribe(() => {
    historySignal.set(runtime.history.getHistory());
  });
  destroyRef.onDestroy(unsub);

  return {
    history: historySignal.asReadonly(),
    jump: (index: number) => runtime.history.jump(index),
  };
}

export function injectThemeLifecycle() {
  const runtime = resolveRuntime();
  return {
    on: (event: ThemeLifecycleEventName, listener: (data: unknown) => void) => runtime.lifecycle.on(event, listener),
  };
}

export function injectThemePacks() {
  const runtime = resolveRuntime();
  return (pack: ThemePack<any>) => runtime.use(pack);
}

export interface ThemeScheduleController {
  /** Reactive `Signal` of the schedule state: `enabled`, `active`, `status`,
   *  `sunrise`, `sunset`, `nextTransition`, `nextActivation`,
   *  `nextDeactivation`. */
  state: Signal<ThemeScheduleState>;
  enable: () => void;
  disable: () => void;
  set: (options: ThemeScheduleSetOptions) => void;
}

/**
 * Reactive access to the runtime's sunrise/sunset scheduling controller.
 * Returns `null` when the runtime was provided without the `scheduled` option.
 *
 * ```ts
 * const schedule = injectThemeSchedule();
 * schedule?.enable();
 * schedule?.disable();
 * schedule?.state().nextTransition;
 * ```
 */
export function injectThemeSchedule<T extends ThemeDefinition = ThemeDefinition>(): ThemeScheduleController | null {
  const runtime = resolveRuntime<T>();
  const schedule = runtime.schedule ?? null;
  const destroyRef = inject(DestroyRef);

  const state = signal<ThemeScheduleState>(
    schedule?.state ?? EMPTY_THEME_SCHEDULE_STATE,
  );

  if (schedule) {
    const unsub = schedule.subscribe((next) => state.set(next));
    destroyRef.onDestroy(unsub);
  }

  if (!schedule) return null;

  return {
    state: state.asReadonly(),
    enable: () => schedule.enable(),
    disable: () => schedule.disable(),
    set: (options: ThemeScheduleSetOptions) => schedule.set(options),
  };
}

// packages/react/src/hooks.ts
"use client";

import { useMemo, useSyncExternalStore, useCallback } from "react";
import type { ThemeDefinition, ThemeTokens, ThemeRuntime, ThemeRuntimeSnapshot, ThemePack, ThemeLifecycleEventMap, ThemeSchedule } from "@theme-kit/core";

import { useThemeRuntime as useProviderThemeRuntime } from "./provider";

import { EMPTY_THEME_SCHEDULE_STATE } from "@theme-kit/core";

type ThemeLifecycleEventName = keyof ThemeLifecycleEventMap;

function useThemeSelector<T>(getSnapshot: () => T): T {
  const runtime = useProviderThemeRuntime();

  const subscribe = useCallback(
    (listener: () => void) => {
      const unsubStore = runtime.store.subscribe(listener);
      const unsubSelection = runtime.selection.subscribe
        ? runtime.selection.subscribe(listener)
        : () => {};
      return () => {
        unsubStore();
        unsubSelection();
      };
    },
    [runtime],
  );

  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
}

export function useThemeBatch() {
  const runtime = useProviderThemeRuntime();
  return useCallback((callback: () => void) => runtime.batch(callback), [runtime]);
}

export function useThemeSnapshot() {
  const runtime = useProviderThemeRuntime();
  return useCallback((): ThemeRuntimeSnapshot => runtime.snapshot(), [runtime]);
}

export function useThemeRestore() {
  const runtime = useProviderThemeRuntime();
  return useCallback((snapshot: ThemeRuntimeSnapshot) => runtime.restore(snapshot), [runtime]);
}

export function useThemeTimeTravel() {
  const runtime = useProviderThemeRuntime();

  const history = useSyncExternalStore(
    useCallback((listener: () => void) => runtime.store.subscribe(() => listener()), [runtime]),
    () => runtime.history.getHistory(),
    () => runtime.history.getHistory(),
  );

  const jump = useCallback((index: number) => runtime.history.jump(index), [runtime]);

  return { history, jump };
}

export function useThemeLifecycle() {
  const runtime = useProviderThemeRuntime();

  const subscribe = useCallback(
    (event: ThemeLifecycleEventName, listener: (data: unknown) => void) => {
      const unsubscribe = runtime.lifecycle.on(event, listener);
      return unsubscribe;
    },
    [runtime],
  );

  return { on: subscribe };
}

export function useThemePacks() {
  const runtime = useProviderThemeRuntime();
  return useCallback((pack: ThemePack<any>) => runtime.use(pack), [runtime]);
}

export function useThemeValue<T extends ThemeDefinition>() {
  const runtime = useProviderThemeRuntime<T>();

  return useThemeSelector(() => runtime.store.get());
}

export function useThemeTokens<T extends ThemeDefinition>():
  ThemeTokens | undefined {
  return useThemeValue<T>().tokens;
}

export function useThemeMode() {
  const runtime = useProviderThemeRuntime();

  return useThemeSelector(() => runtime.selection.getSelection().mode);
}

export function useThemeFamily() {
  const runtime = useProviderThemeRuntime();

  return useThemeSelector(() => runtime.selection.getSelection().family);
}

export function useSetThemeMode() {
  const runtime = useProviderThemeRuntime();

  return runtime.selection.setMode;
}

export function useSetThemeFamily() {
  const runtime = useProviderThemeRuntime();

  return runtime.selection.setFamily;
}

export function useToggleTheme() {
  const runtime = useProviderThemeRuntime();

  return runtime.selection.toggleTheme;
}

export function useTheme<T extends ThemeDefinition>() {
  const runtime = useProviderThemeRuntime<T>();

  const theme = useThemeValue<T>();
  const mode = useThemeMode();
  const family = useThemeFamily();

  return useMemo(
    () => ({
      theme,
      mode,
      family,
      setMode: runtime.selection.setMode,
      setFamily: runtime.selection.setFamily,
      toggleTheme: runtime.selection.toggleTheme,
    }),
    [runtime, theme, mode, family],
  );
}

export function useThemeHistory() {
  const runtime = useProviderThemeRuntime();

  const subscribe = useCallback(
    (listener: () => void) => runtime.store.subscribe(() => listener()),
    [runtime],
  );

  const canUndo = useSyncExternalStore(
    subscribe,
    () => runtime.history.canUndo(),
    () => runtime.history.canUndo(),
  );

  const canRedo = useSyncExternalStore(
    subscribe,
    () => runtime.history.canRedo(),
    () => runtime.history.canRedo(),
  );

  return useMemo(
    () => ({
      undo: () => runtime.history.undo(),
      redo: () => runtime.history.redo(),
      canUndo,
      canRedo,
      clear: () => runtime.history.clear(),
    }),
    [runtime, canUndo, canRedo],
  );
}

/**
 * Reactive access to the runtime's sunrise/sunset scheduling controller.
 *
 * Requires the runtime to be created with the `scheduled` option (see
 * `ThemeProvider` / `createThemeRuntime`). Returns `null` when the provider has
 * no schedule configured.
 *
 * ```tsx
 * const schedule = useThemeSchedule();
 * schedule?.enable();
 * schedule?.disable();
 * // schedule.enabled, schedule.active, schedule.sunrise, schedule.sunset,
 * // schedule.nextTransition ... re-render reactively.
 * ```
 */
export function useThemeSchedule(): ThemeSchedule | null {
  const runtime = useProviderThemeRuntime();
  const schedule = runtime.schedule ?? null;

  useSyncExternalStore(
    useCallback(
      (listener: () => void) =>
        schedule ? schedule.subscribe(() => listener()) : () => {},
      [schedule],
    ),
    useCallback(
      () => schedule?.state ?? EMPTY_THEME_SCHEDULE_STATE,
      [schedule],
    ),
    // The schedule state is resolved per-visitor on the client (timezone
    // auto-detection), so it can differ between the server render and the
    // hydrated client. Hydrate with the stable empty snapshot and let the
    // real state replace it immediately after mount — this keeps SSR HTML
    // deterministic and avoids a hydration mismatch.
    useCallback(() => EMPTY_THEME_SCHEDULE_STATE, []),
  );

  return schedule;
}
